
name: Deploy to Alpha
on:
  push:
    branches:
      - release/1.4
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
        
      - name: Build Release AAB
        id: buildRelease
        run: cd android && ./gradlew bundleRelease
        
      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: android/app/build/outputs/bundle/release/app-release.aab
          
      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
        
      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.scuti
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          userFraction: 0.1
          track: alpha
